### ISSUE TITLE
Add Apollo for GraphQL fetching

### ISSUE THREAD

**Issue by noahwaldner** [noahwaldner/community-index#15]
In the Page "Home" add Apollo to fetch Data from a GraphQL endpoint.

Please use the React Hooks Syntax of Apollo ("React.useQuery")
Execute the following Query:

``` 
query fetchUsers {
  user_tbl {
    full_name
    username
  }
}
```

For every User received, Display a "UserPreview" Component and pass "full_name" and "username" as parameters.

**Comment by svnnynior** [comment]
Can I take this ?

**Comment by everek** [comment]
@svnnynior sure, go ahead

**Comment by svnnynior** [comment]
Hi @noahwaldner , I have a few questions. 

First, as I understand, you still have not setup an Apollo Provider and GraphQL endpoint url, right ?
So, should I set that up ? and which endpoint url should it be ?

Second, is the component "UserPreview" that you're talking about is the "ProfilePreview" that has already existed in the project, or is it a new component that I need to create ?

thanks.

**Comment by noahwaldner** [comment]
@svnnynior 
- Yes Apollo Provider needs to be set up
- Yes i mean‘t ProfilePreview (it already exists)
- Graphql endpount URL is `https://community-index.herokuapp.com/v1/graphql `
