### ISSUE TITLE
Create Function for optimized Image loading

### ISSUE THREAD

**Issue by noahwaldner** [noahwaldner/community-index#8]
Adjust Header function so a low res version is loaded at first.
As soon as better Versions are available, they get visible.

**Comment by ujjawaljaiswal2017** [comment]
How should I approach this issue?

**Comment by noahwaldner** [comment]
I would use ajax to load an image in a very low res. as soon as its loaded, i‘d display it and load a better image. as soon as that is loded display it

I think it‘s quite easy to do.

If you use ajax, please use the axios framework

**Comment by ujjawaljaiswal2017** [comment]
Do you intend to use images from unsplash further in the project or it is temporary?

**Comment by noahwaldner** [comment]
It is temporary
