### ISSUE TITLE
Responsive Menu

### ISSUE THREAD

**Issue by noahwaldner** [noahwaldner/community-index#9]
Make the Menu responsive.

For tablets and mobile phones the menu should be visible after a click on the menu icon. (Same as Github)

**Comment by ujjawaljaiswal2017** [comment]
Is it alright if I take this issue?

**Comment by sprakash57** [comment]
Would you mind if i take this up?

**Comment by noahwaldner** [comment]
i think @ujjawaljaiswal2017 is working on it

**Comment by ariakm25** [comment]
can i take this ?

**Comment by noahwaldner** [comment]
Ok 👌🏼
